### ISSUE TITLE
sp does not need to be multiplied by first stage coefficient

### ISSUE THREAD

**Issue by calvinhe** [angusmoore/varexternalinstrument#4]
Hey mate,

In your final step you do the following:

```
sp*coefs[origorder]
```
But ` coefs[origorder]` contains the first-stage stage coefficient from `dependent ~ instrument`. I don't think this is necessary. Once you have `s^p` you don't need to multiply it by anything. As the target vector is the first column of matrix __S__ (equation 14) where `s^p = s_11`

You can change this by replacing:

```
coefs[i] <- firststage$coefficients["instrument"]
```

with just

```
coefs[i] <- 1
```

I could be wrong, but I have cross-checked this numerically by also coding up [Ramey (2016)](https://econweb.ucsd.edu/~vramey/research/Shocks_HOM_Ramey_published_corrected.pdf).

**Comment by angusmoore** [comment]
Thanks for looking at this mate, appreciate it. Quick question: the test that I have fails with this change (i.e. gives a different answer to what I've saved as the test reference). It's so long since I wrote this that I can't remember where I got that reference from, so entirely possible the reference is wrong. 

The reference results I have in the tests just replicate GK, using the data they provide. The test gives a contemporaneous shock to gs1 of 0.22507245; with this change it's 0.19549144. I don't have access to matlab, so I can't test their codes to check what they get, and this difference is so small and their plots (on page 61 of the paper) not high enough fidelity for me to be able to confirm that 0.195 is the right answer. Are you able to run the GK matlab codes and check they get 0.195; I'll update the test if so.
